<?php declare(strict_types=1);
    if(!isset($this->index) && empty($montar)){
        echo "Error fatal plantilla inicio<br>\n";
        exit;
        //header("Location: /Dinamica/fallos/EC_4XX/EC_404/index.php?setdata=Pagina_no_Encontrada");
    }
    //echo "Se ha cargado index<br>\n";
    array_push($this->index, "        <div id="."gralCabecera"." class='"."d-flex justify-content-center"."'>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <img class='"."derootty"."' alt='"."Logo"."' src='"."assets/img/logoDerootty.svg"."' height='"."300"."'/>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h2>_______________________________</h2>\n");
    array_push($this->index, "            <h1>Proyecto deee formación y estudio</h1>\n");
    array_push($this->index, "            <h1>Pagina de inicio</h1>\n");
    array_push($this->index, "            <h2>_______________________________</h2>\n");
    //array_push($this->index, "          </div>\n");
    array_push($this->index, "              <div>\n");
    array_push($this->index, "                  <img class='"."derootty"."' alt='"."Logo"."' src='"."assets/img/rootty.png"."' height='"."300"."'/>\n");
    array_push($this->index, "              </div>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "        </div>\n");
    array_push($this->index, "        <h2>Mira los contadores de tiempo, el objetivo es: Adaptar los servicios de mensajeria y contacto.</h2>\n");
    array_push($this->index, "        <h3>Contador 1</h3>\n");
    array_push($this->index, "        <h4>instalando sistemas y adapatando un laboratorio para estudiar</h4>\n");
    array_push($this->index, "        <p>Sistemas operativos, maquinas virtuales, configuraciones de red, localizacion de documentacion, redaccion de articulos</p>\n");
    array_push($this->index, "        <div class='"."timeLapse1 countdown d-flex justify-content-center"."' data-count='"."2024/01/12"."'>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h3>%tl1a</h3>\n");
    array_push($this->index, "            <h4>Dias</h4>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h3>%tl1b</h3>\n");
    array_push($this->index, "            <h4>Horas</h4>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h3>%tl1c</h3>\n");
    array_push($this->index, "            <h4>Minutos</h4>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h3>%tl1d</h3>\n");
    array_push($this->index, "            <h4>Segundos</h4>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "        </div>\n");
    array_push($this->index, "        <h3>Contador 2</h3>\n");
    array_push($this->index, "        <h4>Adaptando documentacion</h4>\n");
    array_push($this->index, "        <div class='"."timeLapse2 countdown d-flex justify-content-center"."' data-count='"."2024/01/18"."'>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h3>%tl2a</h3>\n");
    array_push($this->index, "            <h4>Dias</h4>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h3>%tl2b</h3>\n");
    array_push($this->index, "            <h4>Horas</h4>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h3>%tl2c</h3>\n");
    array_push($this->index, "            <h4>Minutos</h4>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <h3>%tl2d</h3>\n");
    array_push($this->index, "            <h4>Segundos</h4>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "        </div>\n");
    array_push($this->index, "        <div class='"."profile-badge profile-badge--width-330 profile-badge--dark"."' dir='"."ltr"."'>\n");
    array_push($this->index, "          <div class='"."profile-badge__header profile-badge__header--dark"."'>\n");
    array_push($this->index, "            <span class='"."sr-only"."'>\n");
    array_push($this->index, "              <div class='"."badge-base LI-profile-badge"."' data-locale='"."es_ES"."' data-size='"."large"."' data-theme='"."dark"."' data-type='"."HORIZONTAL"."' data-vanity='"."david-salado-rodriguez-9a55b3268"."' data-version='"."v1"."'>\n");
    array_push($this->index, "                <a class='"."badge-base__link LI-simple-link"."' href='"."https://es.linkedin.com/in/david-salado-rodriguez-9a55b3268?trk=profile-badge"."'>\n");
    array_push($this->index, "                  Mi perfil\n");
    array_push($this->index, "                </a>\n");
    array_push($this->index, "              </div>\n");
    array_push($this->index, "            </span>\n");
    array_push($this->index, "            <icon class='"."profile-badge__header-logo-icon profile-badge__header-logo-icon--dark"."' aria-hidden='"."true"."'>\n");
    array_push($this->index, "              <svg xmlns='"."http://www.w3.org/2000/svg"."' xmlns:xlink='"."http://www.w3.org/1999/xlink"."' viewBox='"."0 0 84 21"."' preserveAspectRatio='"."xMinYMin meet"."' version='"."1.1"."' focusable='"."false"."'>\n");
    array_push($this->index, "                <g class='"."inbug"."' stroke='"."none"."' stroke-width='"."1"."' fill='"."none"."' fill-rule='"."evenodd"."'>\n");
    array_push($this->index, "                  <path d='"."M19.479,0 L1.583,0 C0.727,0 0,0.677 0,1.511 L0,19.488 C0,20.323 0.477,21 1.333,21 L19.229,21 C20.086,21 21,20.323 21,19.488 L21,1.511 C21,0.677 20.336,0 19.479,0"."' class='"."bug-text-color"."' transform='"."translate(63.000000, 0.000000)"."'></path>\n");
    array_push($this->index, "                  <path d='"."M82.479,0 L64.583,0 C63.727,0 63,0.677 63,1.511 L63,19.488 C63,20.323 63.477,21 64.333,21 L82.229,21 C83.086,21 84,20.323 84,19.488 L84,1.511 C84,0.677 83.336,0 82.479,0 Z M71,8 L73.827,8 L73.827,9.441 L73.858,9.441 C74.289,8.664 75.562,7.875 77.136,7.875 C80.157,7.875 81,9.479 81,12.45 L81,18 L78,18 L78,12.997 C78,11.667 77.469,10.5 76.227,10.5 C74.719,10.5 74,11.521 74,13.197 L74,18 L71,18 L71,8 Z M66,18 L69,18 L69,8 L66,8 L66,18 Z M69.375,4.5 C69.375,5.536 68.536,6.375 67.5,6.375 C66.464,6.375 65.625,5.536 65.625,4.5 C65.625,3.464 66.464,2.625 67.5,2.625 C68.536,2.625 69.375,3.464 69.375,4.5 Z"."' class='"."background"."' fill='"."currentColor"."'></path>\n");
    array_push($this->index, "                </g>\n");
    array_push($this->index, "                <g class='"."linkedin-text"."'>\n");
    array_push($this->index, "                  <path d='"."M60,18 L57.2,18 L57.2,16.809 L57.17,16.809 C56.547,17.531 55.465,18.125 53.631,18.125 C51.131,18.125 48.978,16.244 48.978,13.011 C48.978,9.931 51.1,7.875 53.725,7.875 C55.35,7.875 56.359,8.453 56.97,9.191 L57,9.191 L57,3 L60,3 L60,18 Z M54.479,10.125 C52.764,10.125 51.8,11.348 51.8,12.974 C51.8,14.601 52.764,15.875 54.479,15.875 C56.196,15.875 57.2,14.634 57.2,12.974 C57.2,11.268 56.196,10.125 54.479,10.125 L54.479,10.125 Z"."' fill='"."currentColor"."'></path>\n");
    array_push($this->index, "                  <path d='"."M47.6611,16.3889 C46.9531,17.3059 45.4951,18.1249 43.1411,18.1249 C40.0001,18.1249 38.0001,16.0459 38.0001,12.7779 C38.0001,9.8749 39.8121,7.8749 43.2291,7.8749 C46.1801,7.8749 48.0001,9.8129 48.0001,13.2219 C48.0001,13.5629 47.9451,13.8999 47.9451,13.8999 L40.8311,13.8999 L40.8481,14.2089 C41.0451,15.0709 41.6961,16.1249 43.1901,16.1249 C44.4941,16.1249 45.3881,15.4239 45.7921,14.8749 L47.6611,16.3889 Z M45.1131,11.9999 C45.1331,10.9449 44.3591,9.8749 43.1391,9.8749 C41.6871,9.8749 40.9121,11.0089 40.8311,11.9999 L45.1131,11.9999 Z"."' fill='"."currentColor"."'></path>\n");
    array_push($this->index, "                  <polygon fill='"."currentColor"."' points='"."38 8 34.5 8 31 12 31 3 28 3 28 18 31 18 31 13 34.699 18 38.241 18 34 12.533"."'></polygon>\n");
    array_push($this->index, "                  <path d='"."M16,8 L18.827,8 L18.827,9.441 L18.858,9.441 C19.289,8.664 20.562,7.875 22.136,7.875 C25.157,7.875 26,9.792 26,12.45 L26,18 L23,18 L23,12.997 C23,11.525 22.469,10.5 21.227,10.5 C19.719,10.5 19,11.694 19,13.197 L19,18 L16,18 L16,8 Z"."' fill='"."currentColor"."'></path>\n");
    array_push($this->index, "                  <path d='"."M11,18 L14,18 L14,8 L11,8 L11,18 Z M12.501,6.3 C13.495,6.3 14.3,5.494 14.3,4.5 C14.3,3.506 13.495,2.7 12.501,2.7 C11.508,2.7 10.7,3.506 10.7,4.5 C10.7,5.494 11.508,6.3 12.501,6.3 Z"."' fill='"."currentColor"."'></path>\n");
    array_push($this->index, "                  <polygon fill='"."currentColor"."' points='"."3 3 0 3 0 18 9 18 9 15 3 15"."'></polygon>\n");
    array_push($this->index, "                </g>\n");
    array_push($this->index, "              </svg>\n");
    array_push($this->index, "            </icon>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <img class='"."artdeco-entity-image artdeco-entity-image--circle-4 profile-badge__content-profile-image"."' alt='"."Mi perfil"."' src='"."https://media.licdn.com/dms/image/D4D03AQFjbBcJ8B5Qeg/profile-displayphoto-shrink_200_200/0/1705159017246?e=2147483647&amp;v=beta&amp;t=4kmq5t8H1p1s5RXg3RXD32FdDZaAi5v-MonOmH4oXnE"."'/>\n");
    array_push($this->index, "          <div class='"."profile-badge__content"."'>\n");
    array_push($this->index, "            <a class='"."profile-badge__content-profile-name-link profile-badge__content-profile-name-link--dark"."' href='"."https://es.linkedin.com/in/david-salado-rodriguez-9a55b3268?trk=public-profile-badge-profile-badge-profile-name"."' data-tracking-control-name='"."public-profile-badge-profile-badge-profile-name"."' data-tracking-will-navigate='".""."'>\n");
    array_push($this->index, "              Mi perfil en redes\n");
    array_push($this->index, "            </a>\n");
    array_push($this->index, "            <h3 class='"."profile-badge__content-profile-name"."' itemprop='"."name"."'>\n");
    array_push($this->index, "            </h3>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "    <!--\n");
    array_push($this->index, "          <a class='"."profile-badge__cta-btn profile-badge__cta-btn--dark"."' href='"."https://es.linkedin.com/in/david-salado-rodriguez-9a55b3268?trk=public-profile-badge-profile-badge-view-profile-cta"."' target='"."_blank"."' data-tracking-control-name='"."public-profile-badge-profile-badge-view-profile-cta"."' data-tracking-will-navigate='".""."'>\n");
    array_push($this->index, "            Ver perfil\n");
    array_push($this->index, "          </a>\n");
    array_push($this->index, "    -->      \n");
    array_push($this->index, "    <!---->\n");
    array_push($this->index, "        </div>\n");
    array_push($this->index, "        <h2>Accede al temario que estoy desarrollando (todavia inactivo)</h2>\n");
    array_push($this->index, "        <div class='"."dataLapse1 countdown d-flex justify-content-center"."' data-count='"."2024/01/12"."'>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <form action='"."forms/documentacion.php"."' method='"."post"."' role='"."form"."' class='"."php-email-form"."'>\n");
    array_push($this->index, "              <h3><span name='"."objetivos"."'>%dl1a</span></h3>\n");
    array_push($this->index, "              <select name='"."obj"."'>\n");
    array_push($this->index, "                <option selected>%dl1a</option>\n");
    array_push($this->index, "                <!-- <option value=>>'"."value1"."' selected>%dl1a</option> -->\n");
    array_push($this->index, "              </select>\n");
    array_push($this->index, "              <!-- <input type='"."hidden"."' name='"."tarjet"."' value=>>'"."%dl1a"."'/> -->\n");
    array_push($this->index, "              <h4>\n");
    array_push($this->index, "                <button type='"."submit"."' class='"."btn btn-primary"."'><span id='"."scpt_Ojbetivos"."'>Objetivos</span></button>\n");
    array_push($this->index, "              </h4>\n");
    array_push($this->index, "            </form>          \n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <form action='"."forms/documentacion.php"."' method='"."post"."' role='"."form"."' class='"."php-email-form"."'>\n");
    array_push($this->index, "              <h3><span name='"."temario"."'>%dl1b</span></h3>\n");
    array_push($this->index, "                <select name='"."tem"."'>\n");
    array_push($this->index, "                  <option selected>%dl1b</option>\n");
    array_push($this->index, "                  <!-- <option value=>>'"."value1"."' selected>%dl1b</option> -->\n");
    array_push($this->index, "                </select>\n");
    array_push($this->index, "                <!-- <input type='"."hidden"."' name='"."UUID_tem"."'>%ds1b</input> -->\n");
    array_push($this->index, "              <!-- <input type='"."hidden"."' name='"."tem"."' value=>>"."%dl2"."/> -->\n");
    array_push($this->index, "              <h4>\n");
    array_push($this->index, "                <button type='"."submit"."' class='"."btn btn-primary"."'><span id='"."scpt_Temario"."'>Temario</span></button>\n");
    array_push($this->index, "              </h4>\n");
    array_push($this->index, "            </form>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <form action='"."forms/documentacion.php"."' method='"."post"."' role='"."form"."' class='"."php-email-form"."'>\n");
    array_push($this->index, "              <h3><span name='"."seccion"."'>%dl1c</span></h3>\n");
    array_push($this->index, "              <select name='"."sec"."' hidden>\n");
    array_push($this->index, "                <option selected>%dl1c</option>\n");
    array_push($this->index, "                <!-- <option value=>>'"."value1"."' selected>%dl1c</option> -->\n");
    array_push($this->index, "              </select>\n");
    array_push($this->index, "              <input type='"."hidden"."' name='"."sec"."' value=>>"."%dl1c"."/>\n");
    array_push($this->index, "              <h4>\n");
    array_push($this->index, "                <button type='"."submit"."' class='"."btn btn-primary"."'><span id='"."scpt_Seccion"."'>Seccion</span></button>\n");
    array_push($this->index, "              </h4>\n");
    array_push($this->index, "            </form>    \n");      
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div>\n");
    array_push($this->index, "            <form action='"."forms/documentacion.php"."' method='"."post"."' role='"."form"."' class='"."php-email-form"."'>\n");
    array_push($this->index, "              <h3><span name='"."ejercicios"."'>%dl1d</span></h3>\n");
    array_push($this->index, "              <select name='"."sec"."' hidden>\n");
    array_push($this->index, "                <option selected>%dl1d</option>\n");
    array_push($this->index, "                <!-- <option value=>>'"."value1"."' selected>%dl1d</option> -->\n");
    array_push($this->index, "              </select>\n");
    array_push($this->index, "              <input type='"."hidden"."' name='"."ejer"."' value=>>"."%dl4"."/>\n");
    array_push($this->index, "              <h4>\n");
    array_push($this->index, "                <button type='"."submit"."' class='"."btn btn-primary"."'><span id='"."scpt_Ejercicios"."'>Ejercicios</span></button>\n");
    array_push($this->index, "              </h4>\n");
    array_push($this->index, "            </form>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "        </div>\n");
    array_push($this->index, "        <div class='"."subscribe"."'>\n");
    array_push($this->index, "          <h4> Servicios de mensajeria, incorporan estas librerias en php: <a href='"."https://github.com/PHPMailer/PHPMailer"."'>PHPMailer</a></h4>\n");
    array_push($this->index, "          <form action='"."forms/notify.php"."' method='"."post"."' role='"."form"."' class='"."php-email-form"."'>\n");
    array_push($this->index, "            <div class='"."subscribe-form"."'>\n");
    array_push($this->index, "              <input type='"."email"."' name='"."email"."'/><input type='"."submit"."' value=>>'"."Subscribe"."'/>\n");
    array_push($this->index, "            </div>\n");
    array_push($this->index, "            <div class='"."mt-2"."'>\n");
    array_push($this->index, "              <div class='"."loading"."'>Cargando...</div>\n");
    array_push($this->index, "              <div class='"."error-message"."'></div>\n");
    array_push($this->index, "              <div class='"."sent-message"."'>Tus comentarios fueron enviados. ¡Gracias!</div>\n");
    array_push($this->index, "            </div>\n");
    array_push($this->index, "          </form>\n");
    array_push($this->index, "        </div>\n");
    array_push($this->index, "        <div class='"."social-links text-center"."'>\n");
    array_push($this->index, "          <!-- <a href='"."#"."' class='"."twitter"."'><i class='"."bi bi-twitter"."'></i></a> -->\n");
    array_push($this->index, "          <!-- <a href='"."#"."' class='"."facebook"."'><i class='"."bi bi-facebook"."'></i></a> -->\n");
    array_push($this->index, "          <!-- <a href='"."#"."' class='"."instagram"."'><i class='"."bi bi-instagram"."'></i></a> -->\n");
    array_push($this->index, "          <!-- <a href='"."https://derootty.blogspot.com/"."' class='"."btn btn-primary btn-sm"."'><i class='"."bi bi-blogger"."'></i></a> -->\n");
    array_push($this->index, "          <!-- <a href='"."https://derootty.blogspot.com/"."' class='"."blogspot"."'><i class='"."bi bi-blogger"."'></i></a> -->\n");
    array_push($this->index, "          <!-- <a href='"."https://derootty.blogspot.com/"."' class='"."blogspot"."'><i class='"."bi bi-blogger"."'></i></a> -->\n");
    array_push($this->index, "          <a href='"."https://my.linkedin.com/in/david-salado-rodriguez-97b9bb228?trk=org-employees"."' class='"."linkedin"."'><i class='"."bi bi-blogger"."'></i></a>\n");
    array_push($this->index, "        </div>\n");
    array_push($this->index, "<flowCode||value=>>'main'||position=>".count($this->index).">");
    array_push($this->index, "          <div class='"."row content"."'>\n");
    array_push($this->index, "            <div class='"."col-lg-12 pt-4 pt-lg-0"."'>\n");
    array_push($this->index, "            <h2>Objetivos mas inmediatos</h2>\n");
    array_push($this->index, "            <h3>Habilitar servicios generales de este front end:</h3>\n");
    array_push($this->index, "            <h4>Levantando servicios web de comunicacion</h4>\n");
    array_push($this->index, "            <p>\n");
    array_push($this->index, "              Demostrar que el lenguaje PHP cumple con las maximas de script que puede garantizar el principo de minima accion.\n");
    array_push($this->index, "            </p>\n");
    array_push($this->index, "            <h2>Ejercicio</h2>\n");
    array_push($this->index, "            <div class='"."container text-center"."'>\n");
    array_push($this->index, "                <div class='"."row align-items-start"."'>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    <form action='"."/main.php"."' method='"."post"."' name='"."exer0"."' id='"."UUID0"."'>\n");
    array_push($this->index, "                      <ul>\n");
    array_push($this->index, "                        <li>\n");
    array_push($this->index, "                          <i class='"."bi bi-check"."'></i> Generacion segura de formularios con base UUID\n");
    array_push($this->index, "                          <ul>\n");
    array_push($this->index, "                            <li>\n");
    array_push($this->index, "                              <i class='"."bi bi-check"."'></i>\n");
    array_push($this->index, "                              <div class='"."form-check"."'>\n");
    array_push($this->index, "                                <input type='"."radio"."' class='"."form-check-input"."' value=>>'"."UUID_00"."' id='"."radio1"."' name='"."rdnVal"."' />\n");
    array_push($this->index, "                                <label for='"."radio1"."' class='"."form-check-label"."'> de contacto</label>\n");
    array_push($this->index, "                              </div>\n");
    array_push($this->index, "                              <input type='"."hidden"."' value=>>'"."00_sendme"."' name='"."formType_00"."'/>\n");
    array_push($this->index, "                            </li>\n");
    array_push($this->index, "                            <li>\n");
    array_push($this->index, "                              <i class='"."bi bi-check"."'></i>\n");
    array_push($this->index, "                              <div class='"."form-check"."'>\n");
    array_push($this->index, "                                <input type='"."radio"."' class='"."form-check-input"."' value=>>'"."UUID_01"."' id='"."UUID1"."' name='"."rdnVal"."' />\n");
    array_push($this->index, "                                <label for='"."radio1"."' class='"."form-check-label"."'> de login</label>\n");
    array_push($this->index, "                              </div>\n");
    array_push($this->index, "                              <input type='"."hidden"."' value=>>'"."01_logit"."' name='"."formType_01"."'/>\n");
    array_push($this->index, "                            </li>\n");
    array_push($this->index, "                            <li>\n");
    array_push($this->index, "                              <i class='"."bi bi-check"."'></i>\n");
    array_push($this->index, "                              <div class='"."form-check"."'>\n");
    array_push($this->index, "                                <input type='"."radio"."' class='"."form-check-input"."' value=>>'"."UUID_02"."' id='"."UUID2"."' name='"."rdnVal"."' />\n");
    array_push($this->index, "                                <label for='"."radio1"."' class='"."form-check-label"."'> de carrito de compras</label>\n");
    array_push($this->index, "                              </div>\n");
    array_push($this->index, "                              <input type='"."hidden"."' value=>>'"."02_shopon"."' name='"."formType_02"."'/>\n");
    array_push($this->index, "                            </li>\n");
    array_push($this->index, "                            <li>\n");
    array_push($this->index, "                              <i class='"."bi bi-check"."'></i>\n");
    array_push($this->index, "                              <div class='"."form-check"."'>\n");
    array_push($this->index, "                                <input type='"."radio"."' class='"."form-check-input"."' value=>>'"."UUID_03"."' id='"."UUID3"."' name='"."rdnVal"."' />\n");
    array_push($this->index, "                                <label for='"."radio1"."' class='"."form-check-label"."'> pasarela de pagos</label>\n");
    array_push($this->index, "                              </div>\n");
    array_push($this->index, "                              <input type='"."hidden"."' value=>>'"."03_payme"."' name='"."formType_03"."'/>\n");
    array_push($this->index, "                            </li>\n");
    array_push($this->index, "                            <li>\n");
    array_push($this->index, "                              <i class='"."bi bi-check"."'></i>\n");
    array_push($this->index, "                              <div class='"."form-check"."'>\n");
    array_push($this->index, "                                <input type='"."radio"."' class='"."form-check-input"."' value=>>'"."UUID_04"."' id='"."UUID4"."' name='"."rdnVal"."' />\n");
    array_push($this->index, "                                <label for='"."radio1"."' class='"."form-check-label"."'> informacion</label>\n");
    array_push($this->index, "                              </div>\n");
    array_push($this->index, "                              <input type='"."hidden"."' value=>>'"."04_moreinfo"."' name='"."formType_04"."'/>\n");
    array_push($this->index, "                            </li>\n");
    array_push($this->index, "                            <li>\n");
    array_push($this->index, "                              <i class='"."bi bi-check"."'></i>\n");
    array_push($this->index, "                              <div class='"."form-check"."'>\n");
    array_push($this->index, "                                <input type='"."radio"."' class='"."form-check-input"."' value=>>'"."UUID_05"."' id='"."UUID5"."' name='"."rdnVal"."' />\n");
    array_push($this->index, "                                <label for='"."radio1"."' class='"."form-check-label"."'> Cliente de correo</label>\n");
    array_push($this->index, "                              </div>\n");
    array_push($this->index, "                              <input type='"."hidden"."' value=>>'"."05_mail"."' name='"."formType_05"."'/>\n");
    array_push($this->index, "                            </li>\n");
    array_push($this->index, "                          </ul>\n");
    array_push($this->index, "                        </li>\n");
    array_push($this->index, "                      </ul>\n");
    array_push($this->index, "                      <button type='"."submit"."' class='"."btn btn-primary"."'> Quiero ver el avance... </button>\n");
    array_push($this->index, "                    </form>                      \n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    <ul>\n");
    array_push($this->index, "                      <li>\n");
    array_push($this->index, "                        <i class='"."bi bi-check"."'></i> inferencia de la inversa en codigo GNU/PHP\n");
    array_push($this->index, "                        <ul>\n");
    array_push($this->index, "                          <li><i class='"."bi bi-check"."'></i>... todos los fuentes de wordpress y generacion de documentacion expresando mi opinion funcion a funcion</li>\n");
    array_push($this->index, "                          <li><i class='"."bi bi-check"."'></i>... todos los fuentes del framework Symfony 6, generando la documentacion expresando mi opinion con los objetos que dotan de coherencia al framework. Las funciones y codigo procedural, quedara reflejado como flujo de cohesion entre los diferentes objetos</li>\n");
    array_push($this->index, "                          <li><i class='"."bi bi-check"."'></i>... todos los fuentes de drupal 10, analisis de como una metabase de datos tipo SQL puede elevar el grado de securizacion de un sitio web, en relacion a las tecnicas de programacion basadas en hooks</li>\n");
    array_push($this->index, "                        </ul>\n");
    array_push($this->index, "                      </li>\n");
    array_push($this->index, "                    </ul>\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    <ul>\n");
    array_push($this->index, "                      <li>\n");
    array_push($this->index, "                        <i class='"."bi bi-check"."'></i> Generacion y publicacion de documentacion en\n");
    array_push($this->index, "                        <ul>\n");
    array_push($this->index, "                          <li><i class='"."bi bi-check"."'></i>... wordpress: generacion de documentacion funcion a funcion, proceso a proceso, flujo a flujo, con diagramas y esquemas</li>\n");
    array_push($this->index, "                          <li><i class='"."bi bi-check"."'></i>... framework Symfony 6: generacion de documentacion de los objetos que dotan de coherencia al framework. Las funciones y codigo procedural, quedara reflejado como flujo de cohesion entre los diferentes objetos</li>\n");
    array_push($this->index, "                          <li><i class='"."bi bi-check"."'></i>... drupal 10: analisis de como un meta CMS tipo SQL puede elevar el grado de securizacion de un sitio web, en relacion a un desarrollo personalizado</li>\n");
    array_push($this->index, "                        </ul>\n");
    array_push($this->index, "                      </li>\n");
    array_push($this->index, "                    </ul>\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                </div>\n");
    array_push($this->index, "                <div class='"."row align-items-center"."'>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    One of three columns\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    One of three columns\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    One of three columns\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                </div>\n");
    array_push($this->index, "                <div class='"."row align-items-end"."'>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    One of three columns\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    One of three columns\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col"."'>\n");
    array_push($this->index, "                    One of three columns\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                </div>\n");
    array_push($this->index, "              </div>\n");
    array_push($this->index, "              <p class='"."fst-italic"."'>\n");
    array_push($this->index, "                Publicare horario semanal de cada actividad relacionada con esto y su programacion.\n");
    array_push($this->index, "              </p>\n");
    array_push($this->index, "            </div>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "<flowCode||value=>>'main'||position=>".count($this->index).">");
    array_push($this->index, "          <div class='"."section-title"."'>\n");
    array_push($this->index, "            <h2>Cuando tenga el apartado de librerias de contacto hablitado, deberias probarlo, en serio, tú hazlo... aún no se para qué, pero seguro me hará ilusión</h2>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div class='"."row justify-content-center"."'>\n");
    array_push($this->index, "            <div class='"."col-lg-10"."'>\n");
    array_push($this->index, "              <div class='"."info-wrap"."'>\n");
    array_push($this->index, "                <div class='"."row"."'>\n");
    array_push($this->index, "                  <div class='"."col-lg-4 info"."'>\n");
    array_push($this->index, "                    <i class='"."bi bi-geo-alt"."'></i>\n");
    array_push($this->index, "                    <h4>Localizacion:</h4>\n");
    array_push($this->index, "                    <p>Luis Barrón Street<br>New Logroñok, LR 26005</p>\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col-lg-4 info mt-4 mt-lg-0"."'>\n");
    array_push($this->index, "                    <i class='"."bi bi-envelope"."'></i>\n");
    array_push($this->index, "                    <h4>Email:</h4>\n");
    array_push($this->index, "                    <p>aunpor@configu.rar<br>otra@configurac.ion</p>\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col-lg-4 info mt-4 mt-lg-0"."'>\n");
    array_push($this->index, "                    <i class='"."bi bi-phone"."'></i>\n");
    array_push($this->index, "                    <h4>Llamame, aun no se para qué, pero seguro me hará ilusión:</h4>\n");
    array_push($this->index, "                    <div class='"."contenedor-imagen col-lg-6 info mt-6 mt-lg-0"."'>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."numero"."'/>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropZ"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'/>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropY"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'/>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropX"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'/>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropW"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'/>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropV"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'/>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropU"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropT"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                      <div>\n");
    array_push($this->index, "                        <img class='"."img-cropS"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      </div>\n");
    array_push($this->index, "                    </div>\n");
    array_push($this->index, "                    <div class='"."contenedor-imagen col-lg-6 info mt-6 mt-lg-0"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropR"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropQ"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                    </div>\n");
    array_push($this->index, "                    <div class='"."contenedor-imagen col-lg-6 info mt-6 mt-lg-0"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropX"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropW"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                    </div>\n");
    array_push($this->index, "                    <div class='"."contenedor-imagen col-lg-6 info mt-6 mt-lg-0"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                      <img class='"."img-cropP"."' src='"."assets/img/alfabeto3.png"."' alt='"."Tu imagen"."'>\n");
    array_push($this->index, "                    </div>\n");
    array_push($this->index, "                      <div class='"."dataLapse2"."' data-tac1='"."uno"."'>\n");
    array_push($this->index, "                      <p>\n");
    array_push($this->index, "                        <span id='"."campo1"."'>%dl2a</span><br><span id='"."campo2"."'>%dl2b</span>\n");
    array_push($this->index, "                      </p>\n");
    array_push($this->index, "                    </div>\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                </div>\n");
    array_push($this->index, "              </div>\n");
    array_push($this->index, "            </div>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "          <div class='"."row justify-content-center"."'>\n");
    array_push($this->index, "            <div class='"."col-lg-10"."'>\n");
    array_push($this->index, "              <form action='"."forms/contact.php"."' method='"."post"."' role='"."form"."' class='"."php-email-form"."'>\n");
    array_push($this->index, "                <div class='"."row"."'>\n");
    array_push($this->index, "                  <div class='"."col-md-6 form-group"."'>\n");
    array_push($this->index, "                    <input type='"."text"."' name='"."name"."' class='"."form-control"."' id='"."name"."' placeholder='"."Your Name"."' required>\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                  <div class='"."col-md-6 form-group mt-3 mt-md-0"."'>\n");
    array_push($this->index, "                    <input type='"."email"."' class='"."form-control"."' name='"."email"."' id='"."email"."' placeholder='"."Your Email"."' required>\n");
    array_push($this->index, "                  </div>\n");
    array_push($this->index, "                </div>\n");
    array_push($this->index, "                <div class='"."form-group mt-3"."'>\n");
    array_push($this->index, "                  <input type='"."text"."' class='"."form-control"."' name='"."subject"."' id='"."subject"."' placeholder='"."Subject"."' required>\n");
    array_push($this->index, "                </div>\n");
    array_push($this->index, "                <div class='"."form-group mt-3"."'>\n");
    array_push($this->index, "                  <textarea class='"."form-control"."' name='"."message"."' rows='"."5"."' placeholder='"."Message"."' required></textarea>\n");
    array_push($this->index, "                </div>\n");
    array_push($this->index, "                <div class='"."my-3"."'>\n");
    array_push($this->index, "                  <div class='"."loading"."'>Cargando...</div>\n");
    array_push($this->index, "                  <div class='"."error-message"."'></div>\n");
    array_push($this->index, "                  <div class='"."sent-message"."'>Su mensaje fue enviado. ¡Gracias!</div>\n");
    array_push($this->index, "                </div>\n");
    array_push($this->index, "                <div class='"."text-center"."'><button type='"."submit"."'>Enviar mensaje</button></div>\n");
    array_push($this->index, "              </form>\n");
    array_push($this->index, "            </div>\n");
    array_push($this->index, "          </div>\n");
    array_push($this->index, "<flowCode||value=>>'main'||position=>".count($this->index).">");
